### ISSUE TITLE
Gangs of Legends Data missing

### ISSUE THREAD

**Issue by PhilmacFLy** [BSData/necromunda-underhive#2]
Hey everyone,

GW released a PDF for all the old gangs to be played:
https://necromunda.com/wp-content/uploads/sites/5/2017/11/ENG_Necromunda_Gangs_Of_Legend_Download.pdf
Those data is missing from the repository

**Comment by pinecones** [comment]
Underhive is released with only Goliath and Escher. Gang War is under development after a pause over Christmas. Currently, only Goliath is completed for testing (check my personal repositories), but Escher is on the way and then to continue with the legacy gangs.

**Comment by pinecones** [comment]
Just to follow up, there are different credit costs and other information (for example, Juves don't even exist in Underhive) so I had decided, for simplicity, to create two different datasets.
